[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18" }
tokio = { version = "1.28.2", features = ["full"] }

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
cargo-watch = "8.4.0"